load("@rules_cc//cc:defs.bzl", "cc_binary")

# nixpkgs_package(
#     name = "hello",
#     repositories = { "nixpkgs": "@nixpkgs//:default.nix" }
# )
# nixpkgs_cc_configure(repositories = {"nixpkgs": "@nixpkgs//:default.nix"})

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)
